const quotes = [
    "Your strength lies not in your body, but in your unbeatable soul.",
    "The only true disability is a spirit without ambition.",
    "You are not limited by your abilities; you are only limited by your imagination.",
    "Being different is the trademark of champions.",
    "Your dreams don't need a wheelchair or a crutch; they have wings.",
    "Your smile is the most powerful response to every challenge.",
    "You are a story of persistence walking on this Earth.",
    "The world sees a disability; we see a superpower.",
    "Every difficult move you make is a step toward grand glory.",
    "Your will is an engine that never runs out of fuel.",
    "Don't compare your Chapter 1 to someone else's Chapter 100; focus on your own journey.",
    "You are living proof that 'impossible' is just a word.",
    "Your excellence begins where others think you've finished.",
    "A brave heart breaks all barriers.",
    "You were born to stand out, not to fit in.",
    "Your challenges are what polish your precious metal.",
    "It doesn't matter how you move; what matters is where you want to go.",
    "You are an inspiration to everyone who sees you struggle and smile.",
    "Patience and hard work are the keys to all locked doors.",
    "Your determination is the sun that rises on the toughest days.",
    "Never let anyone set a ceiling for your ambitions.",
    "The beauty of the soul outshines any physical limitation.",
    "Your hidden potential exceeds everyone's expectations; start discovering it.",
    "Every new day is a chance to prove you are a hero.",
    "Disability is surrender, and you chose to fight.",
    "You are not a 'case'; you are a person with a mission.",
    "Believe in yourself, and the world will believe in you too.",
    "Your true heroism is in your daily resilience.",
    "Heroes aren't born; they are made in life's hardest battles.",
    "Make the world adapt to your strength, don't adapt to its weakness.",
    "Your disability is the beginning of an extraordinary success story.",
    "You possess a vision that many lack.",
    "Don't look at what you lost; look at what you can do with what you have.",
    "Willpower creates miracles that the body cannot.",
    "You are the pride of yourself and your family in every step you take.",
    "Life is a school, and you are a professor of resilience.",
    "You are not alone; your persistence is your constant companion.",
    "Every stumbling block is a step on your ladder to success.",
    "Creativity doesn't need limbs; it needs a brilliant mind.",
    "The voice of your ambition is louder than any words of frustration.",
    "You plant hope in the hearts of those around you just by existing.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Be brave enough to live your life in your own special way.",
    "The world needs your unique light; don't let it fade.",
    "Challenging the odds is the specialty you have mastered.",
    "Every attempt you make is a victory in itself.",
    "You don't break the rules; you create new rules for success.",
    "Your steadiness in the face of storms makes you a role model.",
    "There is no mountain too high for someone determined to reach the top.",
    "You are a miracle in yourself; never forget that.",
    "Let your passion be the compass that guides you.",
    "Success tastes sweeter when it comes after hardship.",
    "Your soul is free, and no obstacle can cage it.",
    "You give a new meaning to strength every single day.",
    "Don't seek pity; earn respect through your work and excellence.",
    "Your mind is your strongest muscle; use it well.",
    "Every scar in your soul is a medal of honor for a warrior.",
    "Life loves those who hold on to it despite their pain.",
    "You are making history with your beautiful patience.",
    "Never stop dreaming; dreams are the fuel of the soul.",
    "Your movement might be different, but your goal is the same: the summit.",
    "You have a special magic that lies in your persistence.",
    "Challenge yourself before you challenge the world.",
    "Believing in yourself is half the battle won.",
    "You paint the canvas of your life with colors of resilience and faith.",
    "The greater the difficulty, the greater the pride in reaching the end.",
    "Be the star that lights up the darkness of the impossible.",
    "You don't need wings to fly with your ambition.",
    "Your character defines your value, not your appearance.",
    "Life is full of opportunities for those who search with their hearts.",
    "You are building a bridge of hope over a sea of challenges.",
    "The simple beauty of your strength is in your ability to keep going.",
    "Don't grieve over the past; prepare for the future with power.",
    "You are a master of the art of life and willpower.",
    "Every obstacle increases the toughness of your resolve.",
    "You are a gift to the world; prove it through your uniqueness.",
    "Be proud of everything you've achieved, no matter how small.",
    "Focusing on the possible is the key to happiness.",
    "You create your own reality with your sincere faith.",
    "The road may be long, but you have a longer breath.",
    "You are not just a number; you are a unique fingerprint.",
    "Willpower is what turns dreams into reality.",
    "Be the hero of your own life story.",
    "The world has room for every kind of strength, and yours is special.",
    "You have enough energy to change the world around you.",
    "Calmness and patience are your secret weapons.",
    "Don't look back; success is waiting for you ahead.",
    "You tip the scales with every success you achieve.",
    "Self-love is the first step on the road to greatness.",
    "You prove that the mind is the master of the body.",
    "Optimism is the companion that never leaves your side.",
    "You are a flame that never goes out in the face of despair.",
    "A strong will shortens the longest distances.",
    "You deserve the best, so never settle for less.",
    "Every effort you make today, you will harvest as success tomorrow.",
    "You make the difficult look easy with your persistence.",
    "Be an inspiration to yourself first.",
    "Persistence is what separates the successful from the ordinary.",
    "You are a precious gem; challenges only make you shine brighter.",
    "Keep going; the world is waiting for your great success story."
];
const exercises = {
    mind: [
        {t: "The 5-Second Rule", c: "Count down 5-4-3-2-1 and immediately start the task you've been putting off."},
        {t: "Sensory Check", c: "Identify 5 things you see, 4 things you can touch, and 3 things you hear right now."},
        {t: "Square Breathing", c: "Inhale for 4s, hold for 4s, exhale for 4s, hold for 4s. Repeat 3 times."},
        {t: "Focus Point", c: "Stare at a single point in the room for 60 seconds without shifting your gaze."},
        {t: "Mental Unload", c: "Write down the top 3 thoughts bothering you, then imagine tearing the paper."}
    ],
    body: [
        {t: "Jaw Release", c: "Separate your teeth and let your jaw hang loose. Feel the tension leaving your face."},
        {t: "Shoulder Drop", c: "Raise your shoulders to your ears as high as you can, then drop them suddenly with a deep exhale."},
        {t: "Wrist Circles", c: "Rotate your wrists 10 times in each direction to release pressure from typing."},
        {t: "Power Posture", c: "Sit up straight, roll your shoulders back, and take a deep breath into your chest."},
        {t: "Hand Squeeze", c: "Make a tight fist for 5 seconds, then release and spread your fingers as wide as possible."}
    ],
    spirit: [
        {t: "Gratitude Spark", c: "Think of one person you are grateful for today and send them a silent 'thank you'."},
        {t: "Self-Affirmation", c: "Say to yourself: 'I am doing my best, and my best is enough for today'."},
        {t: "Inner Peace", c: "Close your eyes and visualize a calm, safe place for 30 seconds."},
        {t: "Kind Wish", c: "Think of someone you find difficult and wish them peace and happiness silently."},
        {t: "Heart Connection", c: "Place your hand on your heart and feel its beat as a reminder of your strength."}
    ]
};